name = "behalf-task-manager"
main = "worker/index-full.ts"
compatibility_date = "2025-09-16"
compatibility_flags = ["nodejs_compat"]

[vars]
NODE_ENV = "production"

[[d1_databases]]
binding = "DB"
database_name = "behalf"
database_id = "your-d1-database-id"

[[r2_buckets]]
binding = "R2"
bucket_name = "behalf-ingestion"

# KV namespace (optional for caching)
# [[kv_namespaces]]
# binding = "KV"
# id = "your-kv-namespace-id"

# Queues configuration (not implemented yet)
# [[queues.producers]]
# binding = "PARSE_QUEUE"
# queue = "parse-queue"

# [[queues.producers]]
# binding = "CALLBACKS_QUEUE"
# queue = "callbacks-queue"

# [[queues.consumers]]
# queue = "callbacks-queue"
# max_batch_size = 50

[durable_objects]
bindings = [
  { name = "TaskQueue", class_name = "TaskQueue" }
]

[[migrations]]
tag = "v1"
new_classes = ["TaskQueue"]

[observability]
enabled = true
head_sampling_rate = 0.01